"""Part 1 mission record screen sheet (raw 4bpp, 0xC3E4CC, 96 tiles, BG0 charblock 0).

The only loader reference is the literal at 0xB75C40. The sheet holds:
  tiles 64-79 / 80-95   戰 / 績 title, 4x4 tiles (32x32) each, row-major
  tiles 37-41 + 16      日 数 ラ ン ク  small 8x16 glyphs (top n, bottom n+16), ink 10
Digits and rank letters (tiles 0-31/48-63) stay native.

Title glyph masks are a reviewed data asset (data/part1_record_title_glyphs.json),
generated from OkDanDan-Bold (2026-10-08 font rule: large text = OkDanDan; the
earlier Noto Sans CJK KR Black masks were replaced) with generate_title_masks();
the build never needs the font. Outline index 14 and the vertical fill bands
follow the original 戰 profile, stretched over the glyphs' own ink rows. Small glyphs reuse the project's
2350-syllable glyph blob (ink 9 -> 10), so '14日' shares the new '일'.
"""
import hashlib
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEET, TILES = 0xC3E4CC, 96
LOADER_LITERAL = 0xB75C40
TITLE_GLYPHS = os.path.join(BASE, 'data', 'part1_record_title_glyphs.json')
TITLE = (('전', 64), ('적', 80))
SMALL = (('일', 37), ('수', 38), ('랭', 39), ('크', 40), (None, 41))
OUTLINE = 14
# Fill index by pixel row inside the 32x32 cell (original 戰 profile).
BANDS = ((0, 6, 9), (6, 9, 8), (9, 12, 7), (12, 15, 6), (15, 17, 5), (17, 20, 4),
         (20, 23, 3), (23, 26, 2), (26, 32, 1))


def _get(buf, t, x, y):
    b = buf[t * 32 + y * 4 + x // 2]
    return (b >> 4) if x & 1 else b & 15


def _put(buf, t, x, y, v):
    i = t * 32 + y * 4 + x // 2
    buf[i] = (buf[i] & 0x0F) | (v << 4) if x & 1 else (buf[i] & 0xF0) | v


def generate_title_masks(font_path=None, out=TITLE_GLYPHS, box=28):
    """One-time generator (font only needed here): OkDanDan-Bold, largest size
    whose common 전적 line and every glyph width fit box x box (1px outline + no
    edge contact in the 32x32 cell), both glyphs on one baseline."""
    import aw_fonts
    chars = ''.join(ch for ch, _ in TITLE)
    if font_path:
        raise ValueError('the record title is OkDanDan-only (2026-10-08 font rule)')
    size = aw_fonts.okdandan_fit_line(box, chars)
    while max(aw_fonts.okdandan_glyph(ch, size, chars=chars)[1] for ch in chars) > box:
        size -= 1
    masks = {}
    for ch in chars:
        ink, width, height = aw_fonts.okdandan_glyph(ch, size, chars=chars)
        left, top = (32 - width) // 2, (32 - height) // 2
        cells = {(x + left, y + top) for x, y in ink}
        masks[ch] = [''.join('#' if (x, y) in cells else '.' for x in range(32)) for y in range(32)]
    data = {'note': 'Glyph masks for the Part 1 record title 전적 (32x32). Generated by '
                    'tools/part1_record_screen.generate_title_masks from OkDanDan-Bold '
                    f'(sha256 {aw_fonts.OKDANDAN_SHA256}) at {size}px on the common 전적 line, '
                    f'fitting {box}x{box}, threshold 128.',
            'masks': masks}
    with open(out, 'w', encoding='utf-8') as stream:
        json.dump(data, stream, ensure_ascii=False, indent=1)
    return data


# The original 戰/績 ink spans rows 1..30 and BANDS is that absolute profile.
NATIVE_INK_ROWS = (1, 30)


def ink_rows(masks):
    """Common (top, bottom) ink rows of all title glyphs."""
    ys = [y for rows in masks.values() for y, row in enumerate(rows) if '#' in row]
    return min(ys), max(ys)


def band_value(y, rows):
    """Fill index of row y: the native band profile stretched over the glyphs' own
    ink rows, so every band of the gradient stays visible (the OkDanDan glyphs
    are shorter than 戰 and have empty rows between their jamo)."""
    top, bottom = rows
    lo, hi = NATIVE_INK_ROWS
    native = lo + (y - top) * (hi - lo) / max(1, bottom - top)
    return next(v for a, b, v in BANDS if a <= round(native) < b) if 0 <= round(native) < 32 else BANDS[-1][2]


def render_title(buf, ch, first, masks):
    rows = masks[ch]
    extent = ink_rows(masks)
    glyph = {(x, y) for y, row in enumerate(rows) for x, c in enumerate(row) if c == '#'}
    outline = {(x + dx, y + dy) for x, y in glyph for dx in (-1, 0, 1) for dy in (-1, 0, 1)
               if 0 <= x + dx < 32 and 0 <= y + dy < 32 and (x + dx, y + dy) not in glyph}
    if any(x in (0, 31) or y in (0, 31) for x, y in glyph):
        raise AssertionError(f'record title glyph {ch} touches the cell edge')
    for y in range(32):
        fill = band_value(y, extent)
        for x in range(32):
            t = first + (y // 8) * 4 + x // 8
            value = fill if (x, y) in glyph else OUTLINE if (x, y) in outline else 0
            _put(buf, t, x % 8, y % 8, value)


def small_glyph_tiles(ch):
    if ch is None:
        return bytes(32), bytes(32)
    with open(os.path.join(BASE, 'data', 'syllable_to_glyph_2350.json'), encoding='utf-8') as stream:
        mapping = json.load(stream)['map']
    with open(os.path.join(BASE, 'data', 'kor_glyphs_2350.bin'), 'rb') as stream:
        blob = stream.read()
    out = []
    for index in (mapping[ch]['top'], mapping[ch]['bot']):
        tile = bytearray(blob[index * 32:index * 32 + 32])
        for i, b in enumerate(tile):
            lo, hi = b & 15, b >> 4
            lo, hi = (10 if lo == 9 else lo), (10 if hi == 9 else hi)
            if lo not in (0, 10) or hi not in (0, 10):
                raise AssertionError(f'unexpected glyph ink for {ch}')
            tile[i] = lo | (hi << 4)
        out.append(bytes(tile))
    return tuple(out)


ORIGINAL_SHEET_SHA256 = '51d0f0ec3e6b5aaaf8c1e6e78bf72ecf9ba331ed7bc84053bec48f1f83c04c98'


def patch(rom, original):
    import struct
    if struct.unpack_from('<I', original, LOADER_LITERAL)[0] != 0x08000000 + SHEET:
        raise AssertionError('record sheet loader literal changed')
    source = bytes(original[SHEET:SHEET + TILES * 32])
    if hashlib.sha256(source).hexdigest() != ORIGINAL_SHEET_SHA256:
        raise AssertionError('record sheet source changed')
    if bytes(rom[SHEET:SHEET + TILES * 32]) != source:
        raise AssertionError('record sheet already changed by another writer')
    buf = bytearray(source)
    with open(TITLE_GLYPHS, encoding='utf-8') as stream:
        masks = json.load(stream)['masks']
    for ch, first in TITLE:
        render_title(buf, ch, first, masks)
    for ch, top in SMALL:
        a, b = small_glyph_tiles(ch)
        buf[top * 32:top * 32 + 32] = a
        buf[(top + 16) * 32:(top + 17) * 32] = b
    changed = {i // 32 for i in range(len(buf)) if buf[i] != source[i]}
    allowed = set(range(64, 96)) | {t for _, n in SMALL for t in (n, n + 16)}
    if not changed <= allowed:
        raise AssertionError('record sheet patch touched unexpected tiles')
    rom[SHEET:SHEET + TILES * 32] = buf
    return len(changed)
